'use client';
import {useCallback,useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Compass,ArrowUpRight,Plus,Users,MapPin,Plane,Music,Wallet,Check,NotebookPen,Copy,RefreshCw,Sun,Moon,Download,Trash2,Pencil,Lock,ExternalLink} from 'lucide-react';
import {days,essentials,seedEntries,topTen} from '@/lib/guide';
import {kinds,labels,fieldSpecs,cost,durationHours,safeUrl,type Kind,type Fields,type Entry} from '@/lib/travel';
type Group={id:string;name:string;owner:string;invite:string};
type Cloud={user:{id:string;name:string}|null;groups:Group[];entries:Entry[];members?:{name:string}[]};
const empty:Cloud={user:null,groups:[],entries:[]};
const icons={route:MapPin,flight:Plane,music:Music,budget:Wallet,checklist:Check,note:NotebookPen};
function Choice({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[]}){return <Select value={value} onValueChange={v=>onChange(v??'')}><SelectTrigger className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export default function TravelApp(){
 const [tab,setTab]=useState('guide'),[cloud,setCloud]=useState<Cloud>(empty),[group,setGroup]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failure,setFailure]=useState(''),[search,setSearch]=useState(''),[scene,setScene]=useState('全部场景'),[dark,setDark]=useState(false);
 const [teamOpen,setTeamOpen]=useState(false),[teamName,setTeamName]=useState('国庆印尼旅行搭子'),[invite,setInvite]=useState(''),[editing,setEditing]=useState<Partial<Entry>|null>(null),[draft,setDraft]=useState({title:'',scope:'group' as 'group'|'private',data:{} as Fields}),[formError,setFormError]=useState(''),[trash,setTrash]=useState(false),[sync,setSync]=useState(''),[visible,setVisible]=useState<Kind[]>([...kinds]);
 const refresh=useCallback(async(id:string)=>{const r=await fetch('/api/travel'+(id?'?group='+encodeURIComponent(id):''),{cache:'no-store'});const d=await r.json() as Cloud & {error?:string};if(!r.ok)throw Error(d.error||'读取失败');setCloud(d);setLoaded(true);setSync(new Date().toLocaleTimeString('zh-CN'));setFailure('');return d as Cloud},[]);
 useEffect(()=>{let selected='';try{selected=localStorage.getItem('indonesia-group')||'';setDark(localStorage.getItem('indonesia-theme')==='dark')}catch{}const code=new URLSearchParams(location.search).get('invite');if(code){setInvite(code);setTeamOpen(true)}refresh('').then(d=>{const id=d.groups.some(g=>g.id===selected)?selected:d.groups[0]?.id||'';setGroup(id)}).catch(e=>{setFailure(e.message);setLoaded(true)})},[refresh]);
 useEffect(()=>{if(group)refresh(group).catch(e=>setFailure(e.message));try{localStorage.setItem('indonesia-group',group)}catch{}},[group,refresh]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);try{localStorage.setItem('indonesia-theme',dark?'dark':'light')}catch{}},[dark]);
 useEffect(()=>{if(!group)return;const timer=setInterval(()=>{if(!editing&&!busy&&document.visibilityState==='visible')refresh(group).catch(e=>setFailure(e.message))},15000);return()=>clearInterval(timer)},[group,editing,busy,refresh]);
 const current=cloud.groups.find(g=>g.id===group);
 const post=async(payload:unknown)=>{const r=await fetch('/api/travel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {id?:string;error?:string};if(!r.ok)throw Error(d.error||'操作未完成');return d};
 const act=async(action:string,payload:Record<string,unknown>={})=>{setBusy(true);setMessage('');try{const r=await post({action,group,...payload});if(r.id&&(action==='create'||action==='join')){await refresh(r.id);setGroup(r.id);setTeamOpen(false);history.replaceState({},'',location.pathname)}else await refresh(group);setMessage('已保存到云端');return true}catch(e){setMessage((e as Error).message);return false}finally{setBusy(false)}};
 const inviteUrl=current?`${typeof location!=='undefined'?location.origin:''}/?invite=${encodeURIComponent(current.invite)}`:'';
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setMessage('链接已复制，可以直接发给搭子或转换成二维码')}catch{setMessage('自动复制失败，请从下方文本框手动复制')}};
 const openEdit=(e?:Entry,kind?:Kind)=>{if(!current){setTeamOpen(true);return}const k=e?.kind||kind||'note';setEditing(e||{kind:k});setFormError('');setDraft(e?{title:e.title,scope:e.scope,data:{...e.data}}:{title:'',scope:k==='budget'?'private':'group',data:Object.fromEntries(fieldSpecs[k].map(f=>[f.key,f.options?.[0]||'']).concat(k==='budget'?[['amount','0'],['rate','1'],['people','1']]:[]))})};
 const save=async()=>{setBusy(true);setFormError('');try{await post({action:editing?.id?'update':'add',group,id:editing?.id,version:editing?.version,entry:{kind:editing?.kind,...draft}});setEditing(null);await refresh(group);setMessage('已保存到云端')}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}};
 const template=seedEntries.map((e,i)=>({...e,id:'template-'+i,groupId:'',scope:'group' as const,owner:'',version:1,updatedAt:'',updatedBy:'V9 参考计划',deleted:0}));
 const list=(current?cloud.entries:template).filter(e=>e.kind===tab&&Boolean(e.deleted)===trash&&(!search||[e.title,...Object.values(e.data)].join(' ').toLowerCase().includes(search.toLowerCase()))&&(tab!=='music'||scene==='全部场景'||e.data.scene===scene)).sort((a,b)=>a.kind==='route'?(a.data.date+a.data.time).localeCompare(b.data.date+b.data.time)||Number(a.data.order)-Number(b.data.order):0);
 const budget=current?cloud.entries.filter(e=>e.kind==='budget'&&!e.deleted):[];
 const totals=(status:string,each=false)=>budget.filter(e=>e.data.status===status).reduce((sum,e)=>sum+cost(e.data)[each?'each':'total'],0);
 const routeStops=list.filter(e=>e.kind==='route'&&e.data.place).map(e=>e.data.place);
 const routeLink=routeStops.length>1?`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(routeStops[0])}&destination=${encodeURIComponent(routeStops.at(-1)!)}&waypoints=${encodeURIComponent(routeStops.slice(1,-1).join('|'))}`:'';
 const exportData=()=>{const blob=new Blob([JSON.stringify({group:current?.name,exportedAt:new Date().toISOString(),entries:cloud.entries},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='印尼旅行备份.json';a.click();URL.revokeObjectURL(url);setMessage('已导出你可见的记录，包含你的私人预算，请妥善保存')};
 return <div className="travel"><header><a className="brand" href="/"><Compass/> 岛屿之间 <span>INDONESIA / 2026</span></a><div className="actions"><button className="iconbtn" aria-label="切换明暗主题" onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button onClick={()=>setTeamOpen(true)}><Users size={17}/>{current?.name||'我的旅行小组'}</button></div></header><main>
 <div className="intro"><div><p className="eyebrow">10.01 — 10.09 / 国庆旅行计划</p><h1>去山海之间，<br/>把时间留给风景。</h1><p>科莫多 · 巴厘岛 · 布罗莫</p><div className="chips"><span>V9 · 方案 B</span><span>2 个完整核心日</span><span>10/7 晚回雅加达</span></div></div><div><img src="/padar.jpg" alt="Padar 岛真实山脊与海湾景观"/><div className="photo-credit">Padar Island · <a href="https://commons.wikimedia.org/wiki/File:Padar_Island,_Komodo_National_Park,_Indonesia,_20250822_0929_2659.jpg" target="_blank" rel="noreferrer">Jakub Hałun / Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> · 裁切</div></div></div>
 <div className="cloudbar"><span className="dot"/><span>{!loaded?'正在连接云端…':current?`${current.name} · ${cloud.members?.length||1} 位搭子`:'公开攻略 · 创建小组后，一起编辑计划'}</span>{current&&<span className="muted">{sync&&`上次同步 ${sync}`}</span>}<button className="textbtn" onClick={()=>current?refresh(group).catch(e=>setFailure(e.message)):setTeamOpen(true)}>{current?<><RefreshCw size={14}/>刷新</>:'复制攻略，开始协作'} <ArrowUpRight size={14}/></button></div>
 {failure&&<div className="error" role="alert">{failure} <button onClick={()=>refresh(group).catch(e=>setFailure(e.message))}>重试</button></div>}{message&&<div className="notice" role="status">{message}<button className="textbtn" onClick={()=>setMessage('')}>关闭</button></div>}
 <Tabs value={tab} onValueChange={v=>{setTab(String(v));setSearch('');setTrash(false)}}><TabsList className="navtabs"><TabsTrigger value="guide">旅行攻略</TabsTrigger>{visible.map(k=>{const Icon=icons[k];return <TabsTrigger key={k} value={k}><Icon size={16}/>{labels[k]}</TabsTrigger>})}</TabsList></Tabs>
 {tab==='guide'?<>
 <div className="sectiontop"><div><p className="eyebrow">THE JOURNEY</p><h2>这一次，从海岛到火山</h2></div><button onClick={()=>setTeamOpen(true)}><Plus size={16}/>{current?'管理小组与邀请':'复制到我的小组'}</button></div>
 <div className="cardgrid">{[['01','科莫多','10.02 — 10.04','Padar 山海全景、粉红沙滩、巨蜥与浮潜。优先海况、安全与核心体验。'],['02','巴厘岛 / 罗威纳','10.04 — 10.06','清晨出海看海豚，下午只留给一个喜欢的地方。天气合适时优先滑翔伞。'],['03','布罗莫','10.06 — 10.07','完整保留火山日出、沙海和火山口，再返回雅加达，为国际返程留缓冲。']].map(a=><article key={a[0]}><span className="number">{a[0]}</span><p className="eyebrow">{a[2]}</p><h2>{a[1]}</h2><p>{a[3]}</p></article>)}</div>
 <div className="sectiontop"><h2>每天，怎么走</h2><label className="search"><span className="sr-only">搜索攻略</span><input placeholder="搜索景点、日期或提醒…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="tip">所有时刻以当地时间为准。雅加达 / 泗水 UTC+7，巴厘岛 / Labuan Bajo / 中国 UTC+8。航班为参考计划，预订状态需自行确认。</div>
 <div className="days">{days.filter(d=>JSON.stringify(d).toLowerCase().includes(search.toLowerCase())).map((d)=> <details key={d.date} open={!!search||undefined}><summary><span className="day-date">{d.date.slice(5).replace('-','.')}</span><span><strong>{d.title}</strong><small>{d.tag}</small></span><Plus size={18}/></summary><div className="timeline">{d.items.map((i,n)=><div className="time-row" key={n}><time>{i[0]}</time><div><h3>{i[1]}</h3><p>{i[2]}</p></div></div>)}</div></details>)}</div>
 <div className="sectiontop"><h2>少一点临时慌张</h2></div><div className="essentialgrid">{essentials.filter(e=>JSON.stringify(e).toLowerCase().includes(search.toLowerCase())).map(e=><article key={e.title}><h3>{e.title}</h3><p>{e.text}</p><div className="links">{e.links.map(l=><a key={l[0]} href={l[1]} target="_blank" rel="noreferrer">{l[0]} <ArrowUpRight size={14}/></a>)}</div></article>)}</div></>:<>
 <div className="sectiontop"><div><p className="eyebrow">{current?'OUR TRIP':'TRIP TEMPLATE'}</p><h2>{labels[tab as Kind]}{trash?' · 回收站':''}</h2></div><div className="actions">{current&&<button className="outline" onClick={()=>setTrash(!trash)}><Trash2 size={16}/>{trash?'返回记录':'回收站'}</button>}<button onClick={()=>openEdit(undefined,tab as Kind)}><Plus size={16}/>添加{tab==='note'?'自定义笔记':'记录'}</button></div></div>
 {!current&&<div className="tip">这里是公开模板。创建小组即可复制并编辑；已有邀请链接的搭子请先登录，再加入小组。</div>}
 <div className="toolbar"><input aria-label="搜索记录" placeholder="搜索本模块…" value={search} onChange={e=>setSearch(e.target.value)}/>{tab==='music'&&<Choice value={scene} onChange={setScene} options={['全部场景','布罗莫日出','巴厘岛日落','科莫多山海','路上','其他']}/>}</div>
 {tab==='route'&&<><div className="mapbox"><iframe title="印尼旅行地图" loading="lazy" referrerPolicy="no-referrer" src="https://www.openstreetmap.org/export/embed.html?bbox=105.0%2C-10.6%2C121.2%2C-4.5&layer=mapnik"/><div className="map-caption">雅加达 → 科莫多 → 巴厘岛 / 罗威纳 → 泗水 / 布罗莫 → 雅加达</div></div><div className="tip">按日期、时间及同日顺序安排路线。跨岛段需乘机或乘船，地图道路导航不能替代航班与船程规划。{routeLink&&<a href={routeLink} target="_blank" rel="noreferrer">在地图中查看当前路线 <ExternalLink size={14}/></a>}</div></>}
 {tab==='flight'&&<div className="tip">人工追踪：填写航班号、预订状态和最新确认信息。外部查询打开 FlightAware；本页未接入实时航空数据，不会自动更新延误、登机口或取消状态。</div>}
 {tab==='budget'&&<><div className="stats">{[['预计总额',totals('预算')],['已经支付',totals('已支付')],['预算分摊合计',totals('预算',true)]].map(([l,n])=><article key={l}><p>{l}</p><strong>¥{Number(n).toLocaleString('zh-CN',{maximumFractionDigits:2})}</strong></article>)}</div><div className="tip">只汇总你可见的记录；预算和已支付分开统计，不自动相加。私人账目仅本人可读写；选择“小组共享”才会让搭子看到。汇率由你手动填写。</div></>}
 {tab==='music'&&<div className="tip">如果只存 10 首：{topTen.join(' / ')}。可添加音乐平台分享链接，打开原平台播放。</div>}
 {tab==='checklist'&&<div className="tip">{list.filter(e=>e.data.done==='已完成').length} / {list.length} 项完成 · 勾选后云端同步给可见成员。</div>}
 <div className={tab==='music'?'recordgrid musicgrid':'recordgrid'}>{list.map(e=> <article className={'record '+(e.data.done==='已完成'?'done':'')} key={e.id}><div className="recordtop"><span className="pill">{e.scope==='private'?<><Lock size={12}/>仅自己</>:'小组共享'}</span>{e.data.scene&&<span className="pill">{e.data.scene}</span>}{e.data.date&&<span className="pill">{e.data.date.slice(5)} {e.data.time} {e.data.zone}</span>}{e.data.status&&<span className="pill">{e.data.status}</span>}</div><div className="recordtitle">{e.kind==='checklist'&&<Checkbox aria-label={`完成 ${e.title}`} checked={e.data.done==='已完成'} disabled={!current||busy||trash} onCheckedChange={v=>act('update',{id:e.id,version:e.version,entry:{...e,data:{...e.data,done:v?'已完成':'待完成'}}})}/>}<h3>{e.title}</h3></div>
 {e.kind==='flight'?<><div className="flightpath"><strong>{e.data.from||'出发地'}</strong><Plane size={18}/><strong>{e.data.to||'目的地'}</strong></div><p>{e.data.departure?.replace('T',' ')||'出发待定'} {e.data.departureZone}<br/>{e.data.arrival?.replace('T',' ')||'到达待定'} {e.data.arrivalZone}</p>{durationHours(e.data)!==null&&<p>航程 {durationHours(e.data)?.toFixed(2)} 小时</p>}<p>{e.data.terminal}</p>{e.data.number?<a className="link" target="_blank" rel="noreferrer" href={'https://www.flightaware.com/live/flight/'+encodeURIComponent(e.data.number.replace(/\s/g,''))}>{e.data.number} · 外部航班查询 <ArrowUpRight size={14}/></a>:<small>航班号待补充</small>}</>:e.kind==='budget'?<><strong className="money">{Number(e.data.amount).toLocaleString()} {e.data.currency}</strong><p>折合 ¥{cost(e.data).total.toFixed(2)} · {e.data.people} 人分摊<br/>每人 ¥{cost(e.data).each.toFixed(2)}</p></>:e.kind==='music'?<p className="artist">{e.data.artist}</p>:null}
 {e.data.place&&<a className="link" target="_blank" rel="noreferrer" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(e.data.place)}><MapPin size={14}/>{e.data.place}</a>}{e.data.transport&&<p>交通：{e.data.transport} · 同日顺序 {e.data.order||'未设定'}</p>}{e.data.category&&<p>{e.data.category}</p>}{e.data.notes&&<p className="notes">{e.data.notes}</p>}{e.data.url&&safeUrl(e.data.url)&&<a className="link" target="_blank" rel="noreferrer" href={safeUrl(e.data.url)}>打开{e.kind==='music'?'音乐':'参考'}链接 <ExternalLink size={14}/></a>}
 <div className="recordbottom"><small>{e.updatedAt?`${e.updatedBy} · ${new Date(e.updatedAt).toLocaleString('zh-CN')}`:'V9 参考模板'}</small>{current&&<div className="actions">{trash?<button className="textbtn" disabled={busy} onClick={()=>act('restore',{id:e.id,version:e.version})}>恢复记录</button>:<><button aria-label={`编辑 ${e.title}`} className="textbtn" onClick={()=>openEdit(e)}><Pencil size={15}/>编辑</button><button aria-label={`移入回收站 ${e.title}`} className="textbtn" disabled={busy} onClick={()=>act('delete',{id:e.id,version:e.version})}><Trash2 size={15}/></button></>}</div>}</div></article>)}</div>{!list.length&&<div className="empty"><Compass size={34}/><h3>{trash?'回收站为空':search?'没有找到匹配记录':'给这一趟，添一点自己的安排'}</h3><p>{tab==='budget'?'你的原始费用未公开，请自行添加预算或支出。':'添加记录后，小组成员可以一起完善。'}</p></div>}
 </>}
 <footer><span>国庆印尼旅游 · 内容基于 V9 方案 B · 2026</span><span>公共攻略与小组记录分开保存</span></footer>
 </main>
 <Dialog open={teamOpen} onOpenChange={setTeamOpen}><DialogContent className="team-dialog"><DialogTitle>一起，把旅行计划好</DialogTitle><DialogDescription>公开攻略无需登录。协作使用 ChatGPT 账号登录，加入同一小组后可跨设备编辑。</DialogDescription>{!loaded?<p>正在连接…</p>:!cloud.user?<><a className="solid" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(invite?'/?invite='+encodeURIComponent(invite):'/')}>登录并开始协作 <ArrowUpRight size={16}/></a><p>登录后创建小组，或使用队友发来的邀请链接加入。</p></>:<><p>你好，{cloud.user.name}</p>{cloud.groups.length>0&&<div className="group-list">{cloud.groups.map(g=><button className={g.id===group?'selected':''} key={g.id} onClick={()=>{setGroup(g.id);setTeamOpen(false)}}><Users size={16}/>{g.name}</button>)}</div>}<label>新建旅行小组<input value={teamName} maxLength={80} onChange={e=>setTeamName(e.target.value)}/></label><button className="solid" disabled={busy} onClick={()=>act('create',{name:teamName})}>创建并复制完整攻略</button><label>邀请链接或邀请码<input placeholder="粘贴搭子发来的完整邀请链接" value={invite} onChange={e=>setInvite(e.target.value)}/></label><button className="outline" disabled={busy||!invite} onClick={()=>{let code=invite;try{code=new URL(invite).searchParams.get('invite')||invite}catch{}act('join',{invite:code})}}>加入搭子的小组</button>
 {current&&<><hr/><h3>邀请搭子</h3><p>任何持有小组邀请链接并登录的人都能加入和编辑。普通网站链接只展示公共攻略。</p><input aria-label="小组邀请链接" readOnly value={inviteUrl}/><button className="solid" onClick={()=>copy(inviteUrl)}><Copy size={16}/>复制小组邀请链接</button>{cloud.user.id===current.owner&&<button className="textbtn" disabled={busy} onClick={()=>act('rotate')}>更换邀请链接（旧链接随即失效，已加入成员保留）</button>}<button className="outline" onClick={exportData}><Download size={16}/>导出我可见的全部记录</button></>}
 <hr/><h3>我的页面模块</h3><div className="modulechoices">{kinds.map(k=><label key={k}><Checkbox checked={visible.includes(k)} onCheckedChange={v=>{setVisible(v?[...visible,k]:visible.filter(x=>x!==k));if(!v&&tab===k)setTab('guide')}}/>{labels[k]}</label>)}</div><a className="link" href="/signout-with-chatgpt?return_to=%2F">退出登录</a></>}{message&&<p role="status">{message}</p>}</DialogContent></Dialog>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!busy)setEditing(null)}}><DialogContent className="edit-dialog"><DialogTitle>{editing?.id?'编辑':'添加'}{editing?.kind&&labels[editing.kind]}</DialogTitle><DialogDescription>保存到云端；如果队友已修改同一条记录，会提示你合并。</DialogDescription><form onSubmit={e=>{e.preventDefault();save()}}><label>标题<input required maxLength={160} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>谁可以看到和编辑<Choice value={draft.scope==='private'?'仅自己':'小组共享'} onChange={v=>setDraft({...draft,scope:v==='仅自己'?'private':'group'})} options={editing?.id&&editing.owner!==cloud.user?.id?[draft.scope==='private'?'仅自己':'小组共享']:['仅自己','小组共享']}/></label><div className="formgrid">{editing?.kind&&fieldSpecs[editing.kind].map(f=><label className={f.type==='textarea'?'wide':''} key={f.key}>{f.label}{f.options?<Choice value={draft.data[f.key]||f.options[0]} options={f.options} onChange={v=>setDraft({...draft,data:{...draft.data,[f.key]:v,...(f.key==='currency'&&v==='CNY'?{rate:'1'}:{})}})}/>:f.type==='textarea'?<textarea rows={5} maxLength={8000} value={draft.data[f.key]||''} onChange={e=>setDraft({...draft,data:{...draft.data,[f.key]:e.target.value}})}/>:<input type={f.type||'text'} step={f.type==='number'?'any':undefined} value={draft.data[f.key]||''} onChange={e=>setDraft({...draft,data:{...draft.data,[f.key]:e.target.value}})}/>}</label>)}</div>{formError&&<div className="error" role="alert">{formError}</div>}<button className="solid save" type="submit" disabled={busy}>{busy?'正在保存…':'保存到云端'}</button></form></DialogContent></Dialog>
 </div>
}
